### ISSUE TITLE
Create Chocolatey / Windows RNP package

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/chocolatey-rnp#1]

**Comment by ronaldtse** [comment]
Ping @camobap795

**Comment by CAMOBAP** [comment]
@ronaldtse could you please clarify where the software locates, also please give me write access to this repo (and snap one)

**Comment by ronaldtse** [comment]
The software repo is at https://github.com/rnpgp/rnp/ . You have access.

**Comment by ronaldtse** [comment]
@rrrooommmaaa would you have time to take on this after Homebrew? Thanks!

**Comment by rrrooommmaaa** [comment]
@ronaldtse Of course, I'll take it.

**Comment by ronaldtse** [comment]
Perfect, appreciate it!

**Comment by rrrooommmaaa** [comment]
@ronaldtse Chocolatey package usually contains a script to download .exe (and check sha256 checksum) from some site. Where would our MinGW binaries be located?

**Comment by rrrooommmaaa** [comment]
Though it's recommended to include files in the package, So I can add exe's into the package.

**Comment by ronaldtse** [comment]
@rrrooommmaaa can we have the MinGW binaries uploaded to bintray?

**Comment by rrrooommmaaa** [comment]
@ronaldtse I think we should have `mingw` and `msys2` packages as dependencies in chocolatey.
I'm currently working in this direction.
I was talking about our own binaries:  `rnp.exe` and `rnpkeys.exe`. There is a practice to make user accept license before downloading binaries. If that's not required, we can bundle the binaries inside the package.

**Comment by ronaldtse** [comment]
> There is a practice to make user accept license before downloading binaries. If that's not required, we can bundle the binaries inside the package.

I think it is not necessary for users to interactively accept the license for downloading the binaries, so let's just bundle them.

Thanks!

**Comment by rrrooommmaaa** [comment]
@ronaldtse We would need MSYS2 dlls to run the binaries. On my build system there were about 80Mbytes downloaded and installed (including zlib1, libjson-c and libbz2) for building the RNP.
So we can either:
1) pack them all into Chocolatey package,
2) download them as zip from some repo.
3) try to rebuild them using dependencies with exact versions.
Which would be more appropriate and won't infringe on licenses?
I have a script to deploy MSYS2 and pacman updates handy from another project.

**Comment by ronaldtse** [comment]
@rrrooommmaaa @dewyatt @ni4 I think the best way to distribute on Windows is to statically compile in json-c and zlib (no Chocolately packages), and depend on the bzip2 Chocolatey package (comes with bzip2.dll). 

Thoughts?

**Comment by ni4** [comment]
@ronaldtse @rrrooommmaaa I tried to link rnp statically but got some linking problems so filed an issue rnpgp/rnp#996, also we had rnpgp/rnp#888.

I think it would be better to link everything statically if this is allowed by license(s).

**Comment by ronaldtse** [comment]
@ni4 I believe linking everything statically (the libraries we use) is allowed by license as long as we distribute with the license notice as part of the distribution package.

**Comment by ronaldtse** [comment]
Wait it's not created yet. Will need to upload package to Chocolatey.

**Comment by CAMOBAP** [comment]
@ronaldtse let me know if I can help somehow

**Comment by rrrooommmaaa** [comment]
@ronaldtse GHA?

**Comment by ronaldtse** [comment]
@rrrooommmaaa you mean we should update GHA?

**Comment by rrrooommmaaa** [comment]
> @rrrooommmaaa you mean we should update GHA?

We don't have any GHA in this repository yet.
So the task is actually to add GHA in this repository?

It will also close #4

**Comment by ronaldtse** [comment]
@rrrooommmaaa let's close this task and open two new ones:
* upload package to Chocolatey
* use GHA to re-compile / publish package
