### ISSUE TITLE
Auto-publish package to Chocolatey

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/chocolatey-rnp#6]
As title.

_Originally posted by @ronaldtse in https://github.com/rnpgp/chocolatey-rnp/issues/1#issuecomment-576972704_

**Comment by rrrooommmaaa** [comment]
@ronaldtse can you add chocolate API key to secrets, please?

**Comment by ronaldtse** [comment]
@rrrooommmaaa added as `secrets.CHOCOLATEY_API_KEY`!

**Comment by ronaldtse** [comment]
@rrrooommmaaa the RNP Chocolatey package has been approved. Yeah!!

**Comment by ronaldtse** [comment]
https://chocolatey.org/packages/rnp
